[package]
name = "ithaca-the-enby/oxide"
description = "Luau implementation of Rust features & types."
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
